import fs from 'node:fs'
import path from 'node:path'
import { GENERATED_DIR, operationEntries, readContract, schemaRefName } from './model.mjs'

const HEADER = `// AUTO-GENERATED by scripts/openapi/generate.mjs. DO NOT EDIT.\n\n`

function tsString(value) {
  return JSON.stringify(value)
}

function schemaType(schema, required = false) {
  const ref = schemaRefName(schema)
  if (ref) return ref
  if (schema?.enum) return schema.enum.map(tsString).join(' | ')
  if (schema?.oneOf) return schema.oneOf.map((item) => schemaType(item)).join(' | ')
  if (schema?.type === 'array') return `Array<${schemaType(schema.items ?? {})}>`
  if (schema?.type === 'integer' || schema?.type === 'number') return 'number'
  if (schema?.type === 'boolean') return 'boolean'
  if (schema?.type === 'object') return objectType(schema)
  if (schema?.type === 'string') return 'string'
  if (Array.isArray(schema?.type)) {
    return schema.type.map((item) => (item === 'null' ? 'null' : schemaType({ ...schema, type: item }))).join(' | ')
  }
  return required ? 'unknown' : 'unknown'
}

function objectType(schema) {
  const required = new Set(schema.required ?? [])
  const lines = Object.entries(schema.properties ?? {}).map(([name, property]) => {
    const optional = required.has(name) ? '' : '?'
    return `  ${JSON.stringify(name)}${optional}: ${schemaType(property, required.has(name))}`
  })
  return lines.length ? `{\n${lines.join('\n')}\n}` : 'Record<string, unknown>'
}

function generateTypes(contract) {
  const schemas = contract.components?.schemas ?? {}
  const blocks = Object.entries(schemas)
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([name, schema]) => `export type ${name} = ${schemaType(schema, true)}\n`)
  return HEADER + blocks.join('\n')
}

function successfulResponseSchema(operation) {
  for (const [status, response] of Object.entries(operation.responses ?? {}).sort()) {
    if (/^2\d\d$/.test(status)) {
      return response?.content?.['application/json']?.schema ?? response?.content?.['application/problem+json']?.schema ?? null
    }
  }
  return null
}

function requestSchema(operation) {
  return operation.requestBody?.content?.['application/json']?.schema ?? null
}

function collectRefs(schema, imports) {
  if (!schema || typeof schema !== 'object') return
  const ref = schemaRefName(schema)
  if (ref) {
    imports.add(ref)
    return
  }
  if (schema.items) collectRefs(schema.items, imports)
  for (const item of schema.oneOf ?? []) collectRefs(item, imports)
  for (const property of Object.values(schema.properties ?? {})) collectRefs(property, imports)
}

function operationParameters(pathItem, operation) {
  const merged = [...(pathItem.parameters ?? []), ...(operation.parameters ?? [])]
  const byKey = new Map()
  for (const parameter of merged) byKey.set(`${parameter.in}:${parameter.name}`, parameter)
  return [...byKey.values()]
}

function pascalCase(value) {
  const result = value.replace(/(^|[^A-Za-z0-9]+)([A-Za-z0-9])/g, (_, __, char) => char.toUpperCase())
  if (!/^[A-Za-z_$]/.test(result)) return `Operation${result}`
  return result
}

function generateOperationInput(operationId, parameters, bodySchema, bodyRequired, imports) {
  const lines = []
  for (const parameter of parameters) {
    collectRefs(parameter.schema, imports)
    lines.push(`  ${tsString(parameter.name)}${parameter.required ? '' : '?'}: ${schemaType(parameter.schema)}`)
  }
  if (bodySchema) {
    collectRefs(bodySchema, imports)
    lines.push(`  "body"${bodyRequired ? '' : '?'}: ${schemaType(bodySchema)}`)
  }
  if (!lines.length) return null
  return `export interface ${pascalCase(operationId)}Input {\n${lines.join('\n')}\n}`
}

function generatedOperation(route, method, operation, pathItem, imports, inputBlocks) {
  const responseSchema = successfulResponseSchema(operation)
  collectRefs(responseSchema, imports)
  const responseType = schemaRefName(responseSchema) ?? (responseSchema ? schemaType(responseSchema) : 'void')
  const parameters = operationParameters(pathItem, operation)
  const bodySchema = requestSchema(operation)
  const inputBlock = generateOperationInput(
    operation.operationId,
    parameters,
    bodySchema,
    Boolean(operation.requestBody?.required),
    imports,
  )
  if (inputBlock) inputBlocks.push(inputBlock)

  const inputType = inputBlock ? `${pascalCase(operation.operationId)}Input` : null
  const pathParameters = parameters.filter((parameter) => parameter.in === 'path')
  const queryParameters = parameters.filter((parameter) => parameter.in === 'query')
  const requestFields = [`method: ${tsString(method)}`]
  if (pathParameters.length) {
    const values = pathParameters.map((parameter) => `${tsString(parameter.name)}: input[${tsString(parameter.name)}]`).join(', ')
    requestFields.push(`path: interpolatePath(${tsString(route)}, { ${values} })`)
  } else {
    requestFields.push(`path: ${tsString(route)}`)
  }
  if (queryParameters.length) {
    const values = queryParameters.map((parameter) => `${tsString(parameter.name)}: input[${tsString(parameter.name)}]`).join(', ')
    requestFields.push(`query: { ${values} }`)
  }
  if (bodySchema) requestFields.push('body: input.body')

  const argument = inputType ? `input: ${inputType}` : ''
  return `  ${operation.operationId}: (${argument}) => transport.request<${responseType}>({ ${requestFields.join(', ')} }),`
}

function generateClient(contract) {
  const imports = new Set()
  const inputBlocks = []
  const operationLines = operationEntries(contract).map(({ route, method, operation, pathItem }) =>
    generatedOperation(route, method, operation, pathItem, imports, inputBlocks),
  )

  const importLine = imports.size
    ? `import type { ${[...imports].sort().join(', ')} } from './types.gen'\n\n`
    : ''
  const inputs = inputBlocks.length ? `${inputBlocks.join('\n\n')}\n\n` : ''
  const body = operationLines.length ? `\n${operationLines.join('\n')}\n` : ''
  const interpolate = operationLines.some((line) => line.includes('interpolatePath'))
    ? `\nfunction interpolatePath(template: string, parameters: Record<string, unknown>): string {\n  return template.replace(/\\{([^}]+)\\}/g, (_, name: string) => {\n    const value = parameters[name]\n    if (value === undefined || value === null) throw new Error(\`Missing path parameter: \${name}\`)\n    return encodeURIComponent(String(value))\n  })\n}\n`
    : ''
  return `${HEADER}${importLine}${inputs}export interface ApiTransportRequest {\n  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'\n  path: string\n  query?: Record<string, unknown>\n  body?: unknown\n}\n\nexport interface ApiTransport {\n  request<TResponse>(request: ApiTransportRequest): Promise<TResponse>\n}\n\nexport function createApiClient(transport: ApiTransport) {\n  return {${body}} as const\n}\n${interpolate}`
}

function generateIndex() {
  return `${HEADER}export * from './client.gen'\nexport * from './types.gen'\n`
}

export function generatedFiles(contract = readContract()) {
  return new Map([
    ['client.gen.ts', generateClient(contract)],
    ['index.ts', generateIndex()],
    ['types.gen.ts', generateTypes(contract)],
  ])
}

function normalize(value) {
  return value.replace(/\r\n/g, '\n')
}

function run() {
  const check = process.argv.includes('--check')
  const files = generatedFiles()
  if (!check) fs.mkdirSync(GENERATED_DIR, { recursive: true })

  let mismatch = false
  for (const [name, content] of files) {
    const target = path.join(GENERATED_DIR, name)
    if (check) {
      const existing = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : ''
      if (normalize(existing) !== normalize(content)) {
        console.error(`Generated OpenAPI client is stale: ${path.relative(process.cwd(), target)}`)
        mismatch = true
      }
    } else {
      fs.writeFileSync(target, content)
    }
  }

  if (check) {
    const expected = new Set(files.keys())
    const actual = fs.existsSync(GENERATED_DIR)
      ? fs.readdirSync(GENERATED_DIR).filter((name) => name !== '.gitkeep')
      : []
    for (const name of actual) {
      if (!expected.has(name)) {
        console.error(`Unexpected generated file: ${path.relative(process.cwd(), path.join(GENERATED_DIR, name))}`)
        mismatch = true
      }
    }
  } else {
    const gitkeep = path.join(GENERATED_DIR, '.gitkeep')
    if (fs.existsSync(gitkeep)) fs.unlinkSync(gitkeep)
  }

  if (mismatch) {
    console.error('Run `pnpm openapi:generate` and commit the deterministic output.')
    process.exit(1)
  }
}

if (process.argv[1]?.endsWith('generate.mjs')) run()
